name: Create PR with README Update

on:
  push:
    branches:
      - main # Ou troque para a branch principal do seu projeto

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar nova branch
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          BRANCH_NAME=update-readme-$TIMESTAMP
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Atualizar README.md
        run: |
          echo "commit feito às $(date -u)" >> README.md

      - name: Commit e push
        run: |
          git add README.md
          git commit -m "chore: atualização automática no README"
          git push origin $BRANCH_NAME

      - name: Instalar GitHub CLI
        run: sudo apt-get install gh -y

      - name: Autenticar no GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Criar Pull Request com gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Update" \
            --body "This PR updates README to the latest version." \
            --base main \
            --head ${{ env.BRANCH_NAME }}
